# Site settings
name: Firefox Marketplace User Collections Spec
title: Firefox Marketplace User Collections Spec
email: mhanratty@mozilla.com
description: "Specifications for the eventual redesign of the Firefox Marketplace User Collections"
# these need to be changed for each project
baseurl: "/marketplaceux-usercollections" #this is the github project name WITHOUT the trailing /
url: "https://mhanratty.github.io"  #this the url of the GHPages account your project is hosted at

# Build settings
markdown: kramdown
permalinks: pretty
